### ISSUE TITLE
VMAP support

### ISSUE THREAD

**Issue by maherbeg** [tbuchok/vast-xml#22]
I know this project is called vast-xml, but I'm wondering if VMAP support could be added.

**Comment by tbuchok** [comment]
hi @maherbeg, what did you have in mind specifically? would love to hear your thoughts on VMAP needs and find a way to get it into this module or perhaps it's own. looking forward to hearing more.

**Comment by maherbeg** [comment]
Sure, I'd love to specify ad breaks with multiple ad sources. For instance, we'd like to test out a response with a linear and non linear set of ads and validate the appropriate tracking events.

```xml
<vmap:VMAP xmlns:vmap="http://www.iab.net/vmap-1.0" version="1.0">
    <vmap:AdBreak breakType="linear" timeOffset="start" breakId="0.0.0.1056719217">
        <vmap:AdSource id="1" allowMultipleAds="true" followRedirects="true">
            <vmap:VASTAdData>
                <VAST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="3.0">...</VAST>
           </vmap:VASTAdData>
      </vmap:AdSource>
      <vmap:TrackingEvents>
           <vmap:Tracking event="breakStart">
http://trackingEvent.com
           </vmap:Tracking>
           <vmap:Tracking event="breakEnd">
               http://trackingEvent.com
           </vmap:Tracking>
       </vmap:TrackingEvents>
    </vmap:AdBreak>
    <vmap:AdBreak breakType="nonlinear" timeOffset="00:00:22" breakId="0.2.0.552894500">
         <vmap:AdSource id="2" allowMultipleAds="true" followRedirects="true">
              <vmap:VASTAdData>
                    <VAST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="3.0"/>
              </vmap:VASTAdData>
       </vmap:AdSource>
       <vmap:TrackingEvents>
       <vmap:Tracking event="breakStart">
           http://travkingEvent.com
       </vmap:Tracking>
      <vmap:Tracking event="breakEnd">
             http://trackingEvent.com
      </vmap:Tracking>
   </vmap:TrackingEvents>
  </vmap:AdBreak>
</vmap:VMAP>
```

**Comment by tbuchok** [comment]
strange - this notification went into spam. i think a separate module for this would make a lot of sense.

i'm happy to take the lead and/or contribute on this. any preference? do you have timelines for a production project you need to help -- or is targeting end-february good? interested in jamming on this together?

**Comment by maherbeg** [comment]
I'd be interested in building this out together. No timelines in particular. I'm interested in building out better  unit tests and simpler integration tests for our stack. We're already running our parsers against production servers ;)
