### ISSUE TITLE
How to save the xml as a file?

### ISSUE THREAD

**Issue by wroberts15** [tbuchok/vast-xml#23]
Pretty basic question, but couldn't seem to find an answer (doesn't help that I'm new to node.js) 

Just wondering what I should look into for saving this xml as a file on my server/downloading it after creation - Would the best way be to do something like this 

fs.writeFile('message.txt', vast.xml({ pretty : true, indent : '  ', newline : '\n' }), function (err) {
  if (err) throw err;
});

Just kind of thinking out loud at this point, but is there something built into this package that I can use.. I.e. 

vast.saveFile('/location/to/save');

**Comment by tbuchok** [comment]
hi @wroberts15, good question!

the intention of the module is to generate the VAST XML structure in memory from which you can do anything you'd like! most often, it'll be sent directly over HTTP -- but writing to file is common as well.

you got it -- you simply need to use the `fs` module that ships with node-core -- nothing else. you can see an example of this in the unit tests:

https://github.com/tbuchok/vast-xml/blob/master/test/index.test.js#L14-L16

i don't plan on adding a `saveFile` method, as the example of above is just a couple extra lines of code, and it's less to maintain.

if you're new to node, or you if you feel that `saveFile` is necessary (or both!) -- please don't hesitate to fork this module and add in your own prototype methods that fit your needs. let me know how it goes!

i'll close this as i feel that i've covered the question. please don't hesitate to hollar if you have further questions or need any clarifications.
