### ISSUE TITLE
Cannot generate error 

### ISSUE THREAD

**Issue by wroberts15** [tbuchok/vast-xml#25]
Hey so I'm wondering if it's possible to generate a vast xml with an error and all of the other fields (i.e. ad -> inline -> adsystem, adtitle, creatives, etc). 

As of right now I can only generate the vast xml with an error by doing this

    vast = new VAST({VASTErrorURI : "my.url.com"})

or
 
    vast = new VAST({version : '2.0', VASTErrorURI : "my.url.com" })

it's working as expected. I'm going to try to remove a few of the function calls but as of right now I'm setting the ad, impression, creative, mediafile and it's not letting me set the error (it doesn't show in the xml) and the console is showing this 

    { [Error: connect ECONNREFUSED]
       code: 'ECONNREFUSED',
       errno: 'ECONNREFUSED',
       syscall: 'connect' }

**Comment by wroberts15** [comment]
So maybe this is my issue, 

    if (this.ads.length === 0 && this.VASTErrorURI)
      return response.element('Error').cdata(this.VASTErrorURI).end(options);


I have an ad, so I can't display an error?

**Comment by wroberts15** [comment]
looks like I read that last line wrong, but I'm looking at this now I may try to submit a pull request

**Comment by tbuchok** [comment]
hi @wroberts15, the error:

```
{ [Error: connect ECONNREFUSED]
   code: 'ECONNREFUSED',
   errno: 'ECONNREFUSED',
   syscall: 'connect' }
```

looks like you might be doing something over the network?

this lib doesn't do any network calls -- might you provide a more full example of the issue you're seeing?

**Comment by wroberts15** [comment]
I'm generating an xml file and sending it to an html page as a link -- I'm going to try to trouble shoot for a little while. Am I incorrect by saying that this lib only generates the error node if nothing else (ad, etc) is created?

**Comment by wroberts15** [comment]
Yeah so that console output shows up even when it's working with only the version and VastErrorURI are specified, so that doesn't seem to be the issue

**Comment by tbuchok** [comment]
yes, if there are no `ad`s on the VAST tag, it will show an error.

not sure i'm totally following the comment:

> so that doesn't seem to the be issue

what is `that` in the quote above?

without a more full example, i'm not sure i'm able to help troubleshoot much more.

**Comment by wroberts15** [comment]
That meaning the network issue  ->

    { [Error: connect ECONNREFUSED]
       code: 'ECONNREFUSED',
       errno: 'ECONNREFUSED',
        syscall: 'connect' }

So ^^^ that console output shows up even when I'm getting the vast xml response over the network, which is completely fine. So we can disregard that for now..

Basically I just want the error node in the vast xml with all of the ad's and so on

**Comment by tbuchok** [comment]
yes, you can have an error on each `ad` you attach can attach an `Error`. perhaps docs need updating?

can you review if this is what you wanted?

```js
var VAST = require('./');
var vast = new VAST();
var settings = {
  id: 1,
  sequence: 99,
  structure: 'inline',
  AdSystem: { name: 'ad system name', version: '1.0' },
  AdTitle: 'ad title',
  Error: 'http://error.com' // <= i believe this is what you're looking for
};
vast.attachAd(settings);
vast.xml({ pretty : true, indent : '  ', newline : '\n' });
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
  <VAST version="3.0">
    <Ad id="1" sequence="99">
      <InLine>
        <AdSystem version="1.0">ad system name</AdSystem>
        <AdTitle><![CDATA[ad title]]></AdTitle>
        <Description><![CDATA[]]></Description>
        <Error><![CDATA[http://error.com]]></Error>
       <Creatives/>
     </InLine>
   </Ad>
</VAST>
```

**Comment by wroberts15** [comment]
let me try it out thanks

**Comment by wroberts15** [comment]
Works perfectly, thanks

**Comment by tbuchok** [comment]
:+1:

**Comment by tbuchok** [comment]
@wroberts15 can you take a look if this PR would've made this easier for someone looking for the same thing in the future?

https://github.com/tbuchok/vast-xml/pull/26

with your feedback we can merge this on and hope to help others as they come along!

**Comment by wroberts15** [comment]
Does this work the same for wrapper ads? Can't seem to get it working with this

    wrapperAd = vast2.attachAd({
       id : "theID"
     , structure : 'wrapper'
     , AdSystem : { name : 'adsys', version : '2.0' }
     , AdTitle : 'Title'
     , VASTAdTagURI : "http://the.url.com/foobar.xml"
     , Error : "http://the.url.com/error"
    });

**Comment by tbuchok** [comment]
nope, looks like it could potentially be a bug. feel free to open a new issue addressing "error elements within a wrapper ad" -- and we can take a look.
