### ISSUE TITLE
Custom element support?

### ISSUE THREAD

**Issue by wroberts15** [tbuchok/vast-xml#29]
Hello again,

Just wondering if there is any interest in supporting custom elements. For example, if I wanted to have an esi tag,
    
    <VAST version="3.0">
      <esi:vars>
    ...
      </esi:vars>
    </VAST>

I know that's probably going to fail the vast validation, but I think it would definitely be useful to have.. 

Any thoughts?

**Comment by tbuchok** [comment]
I believe we'd want to drop custom XML into an extension element. Looks like adding that quickly is needed. We can leave this open and I'll hammer that out today.

**Comment by tbuchok** [comment]
@wroberts15 here's what i hhad in mind with the ad-level `Extensions` element:

https://github.com/tbuchok/vast-xml/pull/30

is this what you were thinking? this is passing and should be good to merge, i'll take care of it in a day or so if i don't hear back from you.

**Comment by wroberts15** [comment]
yeah that's definitely what I was thinking

**Comment by tbuchok** [comment]
all set. published to npm @1.2.2

**Comment by tbuchok** [comment]
whoops! npm `@1.2.0`
