### ISSUE TITLE
HTML entities automatically generated

### ISSUE THREAD

**Issue by wroberts15** [tbuchok/vast-xml#31]
I was wondering if there was a way to configure the library not to convert my VASTAdTagURI from the original string to one with html entitites? 

For example when I do 

    ad.attachImpression({
      id: "impression",
      url: "http://foo.bar.com/p<esi:vars></esi:vars>";

it changes it to 
   
    <VASTAdTagURI>http://foo.bar.com/p&lt;esi:vars&gt;&lt;/esi:vars&gt;</VASTAdTagURI>

When I'd rather be getting

`<VASTAdTagURI>http://foo.bar.com/p<esi:vars></esi:vars></VASTAdTagURI>`

**Comment by tbuchok** [comment]
what is the intenton of `<esi:vars></esi:vars>` within a url? is the intention that it will be replaced by the ad server at run-time?

the escaping of the entities is from the [xmlbuilder](https://www.npmjs.com/package/xmlbuilder) dependency for vast-xml. it can drop values in "raw", so editing this isn't a huge deal.

it is a (ever so slightly) potentially breaking change for anyone using the lib, so we'll have to bump to 2.0.0.

i'm curious what the use-case is?

**Comment by wroberts15** [comment]
Basically when the vast is requested if there are any extra params ?a=b the akamai servers look at the url request for the vast and can manipulate the xml before responding. 

But how can I drop values in raw? Will a change be necessary for this library?

**Comment by tbuchok** [comment]
got it. that's perfectly understandable.

https://github.com/tbuchok/vast-xml/blob/master/index.js#L19

rather than:

```
wrapper.element('VASTAdTagURI', ad.VASTAdTagURI);
```

it would need to be updated to use the `element#raw` method:

```
wrapper.element('VASTAdTagURI').raw(ad.VASTAdTagURI);
```

does that make sense? are you on a production deadline? if so, what is it?

**Comment by tbuchok** [comment]
and is this specifically with regard to `VastAdTagURI` in a wrapper tag?

**Comment by wroberts15** [comment]
I would say it's not specific to `VastAdTagURI` but in my case that's what I need it for.. No really production deadline, I'm going to try what you suggested in a minute. 

I really appreciate all the help!

**Comment by wroberts15** [comment]
what is your wrapper referring to in this example? is it `wrapper = new VAST({ version : "3.0" });`

**Comment by wroberts15** [comment]
whoops just saw the link you posted. checking it out now

**Comment by wroberts15** [comment]
okay that was my bad.. so a change may be necessary for the lib.. would it be possible to do that without a change do you think?

**Comment by tbuchok** [comment]
[anything's possible](https://www.youtube.com/watch?v=zyjOy7fRzs0) -- but i think the library right now will always escape elements like the `esi:*` stuff you're looking to include.

can you try it on a few other "elements" -- like tracking events, impressions, etc?

most of those are wrapped in `cdata`, which i don't think will escape -- so it could be limited to a small subeset, including `VastAdTagUri`. it'd be helpful if you tried a few and then we could move on from those results!

**Comment by wroberts15** [comment]
definitely not happening to anything in cdata
I'll try a few other ones in a moment, something just came up

**Comment by wroberts15** [comment]
Yeah so that worked, I'm getting the correct xml with the change to wrapper.element#raw etc. but I'm getting a Namespace prefix esi error, which is slightly obnoxious.

What are your thoughts on this issue? Would a configuration parameter along the lines of UseRaw: true or something be useful?

**Comment by tbuchok** [comment]
we might not need to do raw, and at the same time avoid the browser error you mentioned (which obviously is unrelated to this lib).

try pulling down branch `origin/vast-ad-tag-uri-do-not-escape` and see if that helps you. if that works, then we can merge. it just simply wraps the wrapper "vast ad tag uri" in cdata -- which should help!

passes validation too :+1:

**Comment by wroberts15** [comment]
I'll give that a shot today, should be good if everything works the same even if wrapped in cdata

**Comment by wroberts15** [comment]
That branch definitely works for me if you want to merge it!

**Comment by tbuchok** [comment]
thanks for taking a look. merged and published to npm @1.3.0

**Comment by wroberts15** [comment]
Just wondering what you think of just wrapping all of the elements generated in CDATA?
E.g. AdSystem -- 

It may not be useful for Duration, but I'm just wondering if it would be more foolproof to wrap all elements that generate text in the element with CDATA- what are your thoughts?

**Comment by tbuchok** [comment]
would prefer to adjust based on a needs rather than assume one manner is more foolproof than another. does that answer your question?

some elements fail if wrapped in cdata if i remember correctly, but i could be misremembering :)

**Comment by wroberts15** [comment]
Well it's not a necessarily a need, I'm just seeing these entities generated in spots that may not be expected, at least by me. 

Do you remember exactly where you saw that some elements fail, is it running it against the validator? I'm not sure I've ever tried the validator provided in this lib, just google video inspector

**Comment by wroberts15** [comment]
Just saying I wouldn't want to change the lib for myself-- would an extra param specifying cdata be an improvement? I would try to work on that-- you wouldn't need to

**Comment by tbuchok** [comment]
looks like icon was the only one that failed, as this is isn't urgent -- i'll jump back on this in a bit -- but looks like this might work out okay:

**Comment by tbuchok** [comment]
sorry, hit enter too early:

https://github.com/tbuchok/vast-xml/pull/33
