### ISSUE TITLE
Companion banner example doesn't work

### ISSUE THREAD

**Issue by adam-h** [tbuchok/vast-xml#36]
Hey,

The [readme](https://github.com/tbuchok/vast-xml/blob/316fb43f509c74ef95566b1be6d000b25ad7900b/README.md#attach-companion-ad-creatives) example doesn't create a correct companion element, it only has the width and height.

The [test code](https://github.com/tbuchok/vast-xml/blob/316fb43f509c74ef95566b1be6d000b25ad7900b/test/wrapper-with-companion.test.js#L31-L35) for companions works, although I can't figure out how to get the tracking events to be attached.

**Comment by tbuchok** [comment]
Thanks, @adam-h.

Can you send over expected vs actual so we can get a fix in place that works for you?

**Comment by tbuchok** [comment]
@adam-h does this help clarify?

https://github.com/tbuchok/vast-xml/pull/37

if it looks good, do you mind letting me know? i'll merge within a day or so if i haven't heard back from you.

thanks for the note.

**Comment by adam-h** [comment]
@tbuchok Yes it does, sorry for some reason missed these notifications

**Comment by tbuchok** [comment]
@adam-h me too. closing and merging now.
